pipeline {
    agent any

    stages {
        stage('Detect Changes & Trigger Builds') {
            steps {
                script {
                    // 1. Obter a lista de pastas alteradas no último commit
                    def changedFiles = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim().split('\n')

                    // Definir os teus serviços e os nomes dos respetivos Jobs no Jenkins
                    def services = [
                        'lms-authnusers': 'usersnauth',
                        'lms-reader': 'odsoft-p2-readers',
                        'lms-books': 'odsoft-p2-books',
                        'lms-authors': 'odsoft-p2-authors'
                        'lms-genre': 'odsoft-p2-genre'
                    ]

                    def triggered = false

                    // 2. Verificar cada pasta e disparar o build correspondente
                    services.each { folder, jobName ->
                        if (changedFiles.any { it.startsWith(folder + "/") }) {
                            echo "Branch detetada no Orchestrator: ${env.BRANCH_NAME}"
                            echo "Alteração detetada em: ${folder}. A disparar ${jobName}..."
                            build job: jobName, wait: false, parameters: [string(name: 'BRANCH', value: env.BRANCH_NAME ?: 'main')]
                            triggered = true
                        }
                    }

                    if (!triggered) {
                        echo "Nenhuma alteração detetada nas pastas dos microserviços."
                    }
                }
            }
        }
    }
}