pipeline {
    agent any

    environment {
        // ID da credencial que criaste no Jenkins para o Docker Hub
        DOCKER_CREDS = 'docker-hub-credentials'
        DOCKER_REGISTRY = "carlosp2818"
        APP_USERS = "lms-authnusers"
    }

    stages {
        stage('Build & Push with Plugin') {
            steps {
                script {
                    // 1. Build da imagem usando o contexto da pasta correta
                    // O plugin procura o Dockerfile automaticamente na pasta indicada
                    def userImage = docker.build("${DOCKER_REGISTRY}/${APP_USERS}:${env.BRANCH_NAME}-${env.BUILD_ID}", "-f ../users/Dockerfile ../users")

                    // 2. Login e Push automáticos
                    // 'docker-hub-credentials' deve ser do tipo "Username with password" no Jenkins
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDS) {
                        userImage.push()
                        userImage.push('latest') // Opcional: faz push também como latest
                    }
                }
            }
        }

        stage('Deploy with Compose') {
            steps {
                echo "Fazendo deploy via Compose..."
                dir('../lms-authnusers') {
                    // Para o Compose, ainda usamos o SH porque o plugin foca em imagens individuais
                    sh "docker compose up -d"
                }
            }
        }
    }
}