pipeline {
    agent any

    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Branch a construir')
    }

    environment {
        DOCKER_REGISTRY_CREDENTIALS = 'docker-hub-credentials'
        DOCKER_IMAGE_NAME = 'lms-authnusers'
        DOCKER_NAMESPACE = 'cralos062'
        IMAGE_FULL_NAME = "${DOCKER_NAMESPACE}/${DOCKER_IMAGE_NAME}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Unit Tests') {
            steps {
                dir('lms-authnusers') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('Static Analysis & Mutation') {
            parallel {
                stage('SpotBugs') {
                    steps {
                        dir('lms-authnusers') {
                            sh 'mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.6.2:spotbugs'
                        }
                    }
                }
                stage('Pitest') {
                    steps {
                        dir('lms-authnusers') {
                            sh 'mvn org.pitest:pitest-maven:mutationCoverage'
                        }
                    }
                }
            }
        }

        stage('Package Artifact') {
            steps {
                dir('lms-authnusers') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('lms-authnusers') {
                    script {
                        def shortCommit = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                        def buildTag = "${env.BUILD_NUMBER}-${shortCommit}"

                        def customImage = docker.build("${IMAGE_FULL_NAME}:${buildTag}")

                        docker.withRegistry('https://index.docker.io/v1/', DOCKER_REGISTRY_CREDENTIALS) {
                            customImage.push("${buildTag}")
                            customImage.push("latest")
                            if (params.BRANCH != 'main') { customImage.push(params.BRANCH) }
                        }
                    }
                }
            }
        }

        stage('Deploy & Health Check') {
            steps {
                dir('lms-authnusers') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', DOCKER_REGISTRY_CREDENTIALS) {
                            withEnv(["DOCKER_IMAGE=${IMAGE_FULL_NAME}:latest"]) {
                                sh "docker network create lms_network || true"

                                echo "--- Requisito: Health checks in prod ---"
                                                                timeout(time: 3, unit: 'MINUTES') {
                                                                    waitUntil {
                                                                        def health = sh(script: "docker inspect --format='{{.State.Health.Status}}' users-service", returnStdout: true).trim()
                                                                        echo "Estado atual: ${health}"

                                                                        if (health == "unhealthy") {
                                                                            echo "LOGS DE ERRO DA APP:"
                                                                            sh "docker logs users-service --tail 20"
                                                                            return true //
                                                                        }
                                                                        return (health == "healthy")
                                                                    }
                                                                }
                            }
                        }
                    }
                }
            }
        }

        stage('Smoke Tests') {
            // Smoke tests in staging/dev
            steps {
                dir('lms-authnusers') {
                    sh '''
                        export AUTH_URL="http://localhost:8080/api/public/login"
                        k6 run smoke_test.js || (echo "Smoke tests falharam!" && exit 1)
                    '''
                }
            }
        }
    }

    post {
        failure {
            script {
                echo "--- Automatically revoke release (Rollback) ---"
                dir('lms-authnusers') {
                    // Se algo falhou, o Jenkins tenta reverter para a última imagem estável
                    sh "docker compose down"
                    sh "docker compose up -d"
                }
            }
        }
        always {
            cleanWs()
        }
    }
}